### ISSUE TITLE
Shortcut Path

### ISSUE THREAD

**Issue by Soundbeast1** [MihirGit1/Arina_RainmeterVer#1]
How can i change the shortcut path from Control Panel, i have tried path in quotes and brackets, but doesn't seem to work

**Comment by MihirGrand** [comment]
Navigate to line number 66 in C:\Windows\Users\<YourUserName>\Documents\Rainmeter\Skins\Eww\eww.ini. From here, the config for all the shortcuts starts. Look for the LeftMouseDownAction properties of the objects called [Terminal], [Firefox], [Files], [Notes], [Discord], [Reddit], [Telegram] and set it to the path of the exe you want to launch on click, as shown below -

```
LeftMouseDownAction=["C:\Program Files\Google\Chrome\Application\chrome.exe"]
```

Thus, the object changes to something like this

```
[Terminal]
Meter=Image
X=168
Y=32
W=27
H=27
ImageName=#@#Icons\terminal.png
LeftMouseDownAction=LeftMouseDownAction=["C:\Program Files\Google\Chrome\Application\chrome.exe"]
AntiAlias=1
```

If it still doesn't work, try changing LeftMouseDownAction to LeftMouseUpAction.
